apiVersion: v1
kind: Service
metadata:
  name: sample-node-service
  namespace: sample-node
spec:
  type: NodePort
  selector:
    app: sample-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
